name: publish nuget

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          8.0.x
          9.0.x
          10.0.x

    - name: Set tag to version
      run: dnx DotNetCampus.TagToVersion -t ${{ github.ref }}

    - name: Build with dotnet
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --no-build

    - name: Push generated package to GitHub registry
      run: |
        dotnet nuget push .\artifacts\package\release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NugetKey }}
        dotnet nuget push .\artifacts\package\release\*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }} --api-key ${{ secrets.GITHUB_TOKEN }}
